from tkinter import *
from tkinter.ttk import *
import subprocess, os, base64

root = Tk()
root.title("Activate Windows")
root.geometry("350x80")
root.resizable(False, False)
root.configure(background='white')

icon_code = 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABA5SURBVHic7d1di11ZQsbxpyqV99fOe9J5T2rwwou5mUs/i7d+Ar+Dn2kEQUFQEGZQUBAcFBRaZ2iHlkaRMV7sU3R11d5VSeqcs885z+8HGzockiyaJOe/19pr7b0AALvqqySHi+snx/779t6cowIALux2fvhiP/ll/2Di53xzsJ6xAQAXcD3Jh5y+kz9M8vRLfkEBAACb4UqS9xm/k/86yVJn7QUAAKzPQZI3Gb+Tf51kf50DAQCWZz/Jq4yvy7/Nhnz3bsQgAGDL7CV5nvEn7N8nuTrf0D6NAACAaY9zeqr+JxkeyLsx47guTAAA0O5+xu/kD5PcmXFcKyUAAGhwJ6fX5I++8O/POK7ZCAAAdsWNTO+VfzLjuDaSAABgm1zN6b3yR1/4z7PkvfK7TAAAsGkOMmyXG1uXf5U17pXfZQIAgDkc7ZUfe8L+TXw/rZz/wQCsyl6GI2zH7uTfZQv2yu8yAQDART3J6Tv5w+zAXvldJgAA+BQPMv6SmsMMr6NlywgAAI4c7ZUfW5f/asZxsQICAKDLzfywV/7kl/3jGcfFmgkAgN1ztFd+7E7++YzjYoMIAIDtdDnTe+Vfxl55ziEAADbXpYzvlT+MvfJckD88APPaS/Ii40/Yv0tyZb6hscsEAMB6PM34E/YfklyfcVyUEgAAy/Mw03vlb804LjhFAAB8nrsZv5M/jL3ybBEBAHDazYy/bvYwyaMZxwVLIwCAVtcyvlf+MPbKU0AAALvscoYn6cfu5F9meAIfKgkAYNtdSvI64+vybxafAycIAGAb7GW4Y5/aK395vqHBdhIAwCZ5lum98tdmHBfsHAEArNujjD9h/yH2ysPaCABgFe5l/DCcw8VnwMwEAPClbmV6r/zDGccFfAIBAJzleoa98mN38s9mHBdwQQIAuJLpvfIvYq887CQBAB0uZdgTP3Yn/zr2ykMdAQC7Yz+n98offeG/jb3ywDECALbT5SR/mB/fzb+PvfLAJ7K2B9vpXpJv5x4EsLW+2Z97BADA+gkAACgkAACgkACAT3OQYa/8z+YeCMAy2AUAP7iV4Uv+/bHr6MevM/x9+WWSn841QIBlEQC0eZoff7Efvx7POC6AtRIA7JrLGe7Wx+7i3yW5Od/QADaHAGAb3cn0XfzLONYW4FwCgE20l+FNc2N38e/jVbMAFyYAmMuVDOfTj93Fv83wGloAVkQAsEr3Mn4H/z7Da2ZtQwWYiQDgIvaSfJ3Td/BHX/b35xsaAGcRAJznWoYp+bG7+LdJrs43NAC+lAAgGe7Up+7iv463RgLsHAHQYT/D9riprXN35xsaAHMQALvjeqaPsX2T4al7AEgiALbNo0zfxT+NqXoAPpEA2CyXkrzK9AE4t+cbGgC7RACs381M38UfvXEOAFbKl81qPMn0XfyTGccFAEkEwJc6yPBg3dhdvDfOAbDxBMC025k+xvZVvHEOgC3WHAB7GZ6cnzoA59F8QwOA1dr1ALiSYap+7C7+XbxxDoBSuxAAdzN9F/8y3jgHAKdsQwAcf+Pc2EN33jgHAJ9pUwLgan5449zJu/i3Gd5IBwAsyToD4OiNc2N38d44BwBrtMwA2E/yItMH4Nxb4u8FAFzA5wbA0Rvnxu7i38Qb5wBgK4wFwMNM38U/i6l6ANh6B0n+JD/+or8z64jgYj5u+a8PsBYHSf547kHAEq16hsoMGLATHJIDAIUEAAAU2o81TQCoYwYAAAqZAQCAQmYAAKCQAACAQpYAAKCQGQAAKCQAAKCQJQAAKGQGAAAKCQAAKGQJAAAKmQEAgEICAAAKWQIAgEJmAACgkAAAgEKWAACgkBkAACgkAACgkCUAAChkBgAACgkAAChkCQAACpkBAIBCAgAAClkCAIBCZgAAoJAAAIBClgAAoJAZAAAoJAAAoJAlAAAoZAYAAAoJAAAoZAkAAAqZAQCAQgIAAApZAgCAQmYAAKCQAACAQpYAAKCQGQAAKCQAAKCQJQAAKGQGAAAKCQAAKGQJAAAKmQEAgEICAAAKWQIAgEJmAACgkAAAgEKWAACgkBkAACgkAACgkCUAAChkBgAACgkAAChkCQAACpkBAIBCAgAAClkCAIBCZgAAoJAAAIBClgAAoJAZAAAoJAAAoJAlAAAoZAYAAAoJAAAoZAkAAAqZAQCAQgIAAApZAgCAQmYAAKCQAACAQpYAAKCQGQAAKCQAAKCQJQAAKGQGAAAKCQAAKGQJAAAKmQEAgEICAAAKWQIAgEJmAACgkAAAgEKWAACgkBkAACgkAACgkCUAAChkBgAACgkAAChkCQAACpkBAIBCAgAAClkCAIBCZgAAoJAAAIBClgAAoJAZAAAoJAAAoJAlAAAoZAYAAAqZAQCAQmYAAKCQAACAQpYAAKCQGQAAKCQAAKCQJQAAKGQGAAAKCQAAKGQJAAAKmQEAgEICAAAKWQIAgEJmAACgkAAAgEKWAACgkBkAACgkAACgkCUAAChkBgAACgkAAChkCQAACpkBAIBCAgAAClkCAIBCZgAAoJAAAIBClgAAoJAZAAAoJAAAoJAlAAAoZAYAAAoJAAAoZAkAAAqZAQCAQgIAAApZAgCAQmYAAKCQAACAQpYAAKCQGQAAKCQAAKCQJQAAKGQGAAAKCQAAKGQJAAAKmQEAgEICAAAKWQIAgEJmAACgkAAAgEKWAACgkBkAACgkAACgkCUAAChkBgAACh0k+S7Jb+ceCGyJ7+YewMLH+HsLfDn/fgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwsJfk50l+NvdAYEv8bZI/mHsQSe4m+ee5BwFsrY8HSW5n+McEON/tuQewsBd/b4EL2J97AADA+gkAACgkAACgkAAAgEICAAAKCQAAKCQAAKCQAACAQgIAAPp8FAAAUEgAAEAhAQAAhQQAABQSAABQSAAAQCEBAACFBAAAFBIAAFBIAABAHycBAkAjAQAAhQQAABQSAABQSAAAQCEBAACFBAAAFBIAAFBIAABAIQEAAH2cBAgAjQQAABQSAABQSAAAQCEBAACFBAAAFBIAAFBIAABAIQEAAIUEAAD0cRIgADQSAABQSAAAQCEBAACFBAAAFBIAAFBIAABAIQEAAIUEAAAUEgAA0MdJgADQSAAAQCEBAACFBAAAFBIAAFBIAABAIQEAAIUEAAAUEgAAUEgAAEAfJwECQCMBAACFBAAAFBIAAFBIAABAIQEAAIUEAAAUEgAAUEgAAEAhAQAAfZwECACNBAAAFBIAAFBIAABAIQEAAIUEAAAUEgAAUEgAAEAhAQAAhQQAAPRxEiAANBIAAFBIAABAIQEAAIUEAAAUEgAAUEgAAEAhAQAAhQQAABQSAADQx0mAANBIAABAIQEAAIUEAAAUEgAAUEgAAEAhAQAAhQQAABQSAABQSAAAQB8nAQJAIwEAAIUEAAAUEgAAUEgAAEAhAQAAhQQAABQSAABQSAAAQCEBAAB9nAQIAI0EAAAUEgAAUEgAAEAhAQAAhQQAABQSAABQSAAAQCEBAACFBAAA9HESIAA0EgAAUEgAAEAhAQAAhQQAABQSAABQSAAAQCEBAACFBAAA9HEQEAA0EgAAUEgAAEAhAQAAhQQAABQSAABQSAAAQCEBAACFBAAAFBIAANDHSYAA0EgAAEAhAQAAhQQAABQSAABQSAAAQCEBAACFBAAAFBIAAFBIAABAHycBAkAjAQAAhQQAABQSAABQSAAAQCEBAACFBAAAFBIAAFBIAABAIQEAAH2cBAgAjQQAABQSAABQSAAAQCEBAACFBAAAFBIAAFBIAABAoYMkf5Tk95N8SPL+2PV4xnEBACt0kOQXi+ukW/lxEBy/XiW5tKYxAgDL9fHgjA//K8kvF9dJl5O8zhADJ2cO3iW5vtxxAgDLtLeiX/NZpmcPHqzg94R1+WWSn849iCT3knw79yCArfXtWTMAX+pjkn9bXH8x8vndnJ41OLq+jgcTAWDlVhEA5/ltkr9ZXCddTfI243HwdvE5AHBBcwTAWf4nyT8srpP2k7zI9NLC3TWNEQC23qYFwFn+L8m/LK4/G/n8QcbD4EOSp1nN8w4AsJW2KQDO85vF9dcjn93IsDthLBBeZ9jVAAA1dikAzvJ9kr9bXCddynCuwdjMwbsM5yEAwE5pCYCz/C7JrxbXn458/iTTzx04LRGArSQAzvfN4vrLkc9u58dLC8e3N76M0xIB2ExnngTI+b7L2aclvsn4zIHTEgGYlQBYnf9N8o+L66TjpyWOHYp0f01jBKCUAJjHeacl3sv0cwcvYksjABckADbTf+b80xLHZg7eJrmypjECsMUEwPZxWiIAFyYAdst5pyU+zHQcPFvTGAHYAAKgy68X11+NfHbWaYlv4s8KwE7xjzpHzjst8XWmZw9urmmMACyJAOBT/C7JPy2un498PnZa4tFDio/WNEYAPoMAYBnOOy1xaubAaYkA83ASICv3XZJfLK6Txk5LPJo5eBunJQKsjABgTuedlvg807MHTksEuAABwKb6mORfF9efj3x+/LTEk4cifR2nJQKcSQCwrc46LfFahiWEsZkDpyUCRACwm/47yd8vrpOOn5Y4dpzynTWNEWBWAoA2TksEiHVS+Bw3Mpx58Ku5B5LhGYhv5x4EsLV+sz/3CGCLfJ/N+PIHuDABAACFBAAA9PnoGFbYTntJfi/DYUq3Ymsj8Hm+9xAg7IanGbY1jl13ZxwXsJl+LQBg9z3MdBw8mHFcwHwEAJS7l+k4eDLjuIDVEgDApKNXOY/FwfM4RwS2mQAAvsiNJO8yHgcvY4cRbDoBACzd1QwvXTrM6Th4ncTuI5ifAADW6nKSNxmfOXi7+BxYPQEAbIxLSV5lPA7eZXjNM7AcAgDYCnsZXuM8Fgfvk9ycb2iwlf5DAAC74FmmtzPemXFcsKkEALDzHmU6Du7POC6YkwAAqn2V6Th4POO4YNUEAMCEOzl9ENLR1sZnM44LlkEAAHyBG5meOXgRpySy+QQAwJJdy/Qpia/iICQ2gwAAWKPLGQ48GouDN3EQEusjAAA2xKUMRyVPHYR0db6hsYMEAMAW2M/ZByHdmG9obCkBALDl9nL2QUi35xsaG+zfBQDAbnuc6Tj4asZxMS8BAFDsfsZf2/whycMZx8XqCQAARt3N9MzB0xnHxXIIAAA+281Mx8HXcRDSNhAAACzVtZw+Qvn4QUj78w2NYwQAAGtzJWcfhHQw28j6CAAANsJBzj4I6cp8Q9tJAgCAjbef5GWmD0K6Pt/QtpYAAGCr7SV5ntNhcJghDm7NN7SNJgAA2GlPM71j4e6M45rbNwIAgFYPMx0HD2Yc1zoIAAAYcS/TcfBkxnEtiwAAgM90K9Nx8DzbcRCSAACAJbqe6YOQXmZzDkISAACwJlczfRDS66z3ICQBAAAb4CDDaYhjcfA2yz8ISQAAwIa7lGH5YOzVze8yvH/hcwkAANhie0leZPqUxJsTP08AAMAOe5bxOLj1/1g/Wtp3RN0SAAAAAElFTkSuQmCC'
root.iconphoto(False, PhotoImage(data = icon_code))

frame = Frame(root)
frame.columnconfigure(0, weight=1)
frame.place(relx=0.5, rely=0.5, anchor=CENTER)

def activate():
    global v
    key = ''
    match v.get():
        case 'Windows 10 Home':
            key = 'TX9XD-98N7V-6WMQ6-BX7FG-H8Q99'
        case 'Windows 10 Home N':
            key = '3KHY7-WNT83-DGQKR-F7HPR-844BM'
        case 'Windows 10 Home Single Language':
            key = '7HNRX-D7KGG-3K4RQ-4WPJ4-YTDFH'
        case 'Windows 10 Home Country Specific':
            key = 'PVMJN-6DFY6-9CCP6-7BKTT-D3WVR'
        case 'Windows 10 Professional':
            key = 'W269N-WFGWX-YVC9B-4J6C9-T83GX'
        case 'Windows 10 Professional N':
            key = 'MH37W-N47XK-V7XM9-C7227-GCQG9'
        case 'Windows 10 Enterprise':
            key = 'NPPR9-FWDCX-D2C8J-H872K-2YT43'
        case 'Windows 10 Enterprise N':
            key = 'DPH2V-TTNVB-4X9Q3-TJR4H-KHJW4'
        case 'Windows 10 Education':
            key = 'NW6C2-QMPVW-D7KKK-3GKT6-VCFB2'
        case 'Windows 10 Education N':
            key = '2WH4N-8QGBV-H22JP-CT43Q-MDWWJ'
        case 'Windows 10 Enterprise 2015 LTSB':
            key = 'WNMTR-4C88C-JK8YV-HQ7T2-76DF9'
        case 'Windows 10 Enterprise 2015 LTSB N':
            key = '2F77B-TNFGY-69QQF-B8YKP-D69TJ'
        case "Windows 11 Home":
            key = 'TX9XD-98N7V-6WMQ6-BX7FG-H8Q99'
        case "Windows 11 Home Single Lenguage":
            key = '7HNRX-D7KGG-3K4RQ-4WPJ4-YTDFH'
        case "Windows 11 Pro":
            key = 'W269N-WFGWX-YVC9B-4J6C9-T83GX'
        case "Windows 11 Pro N":
            key = 'MH37W-N47XK-V7XM9-C7227-GCQG9'
        case "Windows 11 Education":
            key = 'NW6C2-QMPVW-D7KKK-3GKT6-VCFB2'
        case "Windows 11 Education N":
            key = '2WH4N-8QGBV-H22JP-CT43Q-MDWWJ'
        case "Windows 11 Enterprise":
            key = 'NPPR9-FWDCX-D2C8J-H872K-2YT43'
        case "Windows 11 Enterprise N":
            key = 'DPH2V-TTNVB-4X9Q3-TJR4H-KHJW4'
        case "Windows 11 Enterprise G":
            key = 'YYVX9-NTFWV-6MDM3-9PT4T-4M68B'
        case "Windows 11 Enterprise G N":
            key = '44RPN-FTY23-9VTTB-MP9BX-T84FV'
        case "Windows 11 Workstations":
            key = 'NRG8B-VKK3Q-CXVCJ-9G2XF-6Q84J'
        case "Windows 11 Ultimate":
            key = 'Q269N-WFGWX-YVC9B-4J6C9-T83GX'
    subprocess.call('slmgr.vbs -upk', shell=True)
    subprocess.call('slmgr /ipk ' + key, shell=True)
    subprocess.call('slmgr /skms kms.digiboy.ir', shell=True)
    subprocess.call('slmgr /ato', shell=True)

v = Combobox(frame, state="readonly", values=[
    "Windows 10 Home",
    "Windows 10 Home N",
    "Windows 10 Home Single Language",
    "Windows 10 Home Country Specific",
    "Windows 10 Professional",
    "Windows 10 Professional N",
    "Windows 10 Enterprise",
    "Windows 10 Enterprise N",
    "Windows 10 Education",
    "Windows 10 Education N",
    "Windows 10 Enterprise 2015 LTSB",
    "Windows 10 Enterprise 2015 LTSB N",
    "Windows 11 Home",
    "Windows 11 Home Single Lenguage",
    "Windows 11 Pro",
    "Windows 11 Pro N",
    "Windows 11 Education",
    "Windows 11 Education N",
    "Windows 11 Enterprise",
    "Windows 11 Enterprise N",
    "Windows 11 Enterprise G",
    "Windows 11 Enterprise G N",
    "Windows 11 Workstations",
    "Windows 11 Ultimate",
])
v.current(0)
v.grid(column=0, row=0, sticky='nesw')

Button(frame, text="Activate", width=35, command=activate).grid(column=0, row=1, sticky='nesw')

root.mainloop()